version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    networks:
      - microservices-network
    depends_on:
      - mongo-auth
    environment:
      - MONGO_URI=mongodb://mongo-auth:27017/auth

  task-service:
    build: ./task-service
    ports:
      - "4001:4001"
    networks:
      - microservices-network
    depends_on:
      - mongo-task
    environment:
      - MONGO_URI=mongodb://mongo-task:27017/tasks

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - auth-service
      - task-service

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"  # Mapea el puerto del frontend al 3001 de tu máquina
    networks:
      - microservices-network

  mongo-auth:
    image: mongo
    networks:
      - microservices-network
    volumes:
      - mongo-auth-data:/data/db

  mongo-task:
    image: mongo
    networks:
      - microservices-network
    volumes:
      - mongo-task-data:/data/db

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-auth-data:
  mongo-task-data:
